### ISSUE TITLE
Firmware: which one to choose?

### ISSUE THREAD

**Issue by hayschan** [valzzu/meshtastic-pcbs#1]
Love your design! Great work.

Which firmware should I choose from the official flasher? Or do I need to change the pins and compile myseslf through PlatformIO?

**Comment by valzzu** [comment]
It's the promicro diy Variant in the flasher

**Comment by hayschan** [comment]
Thanks a lot. Great work. 

I've recommended to a lot of people in the MeshCN.net community. 

We love your work!! 🚀

**Comment by valzzu** [comment]
awesome :) hope to see them in the wild xd

**Comment by valzzu** [comment]
@hayschan btw what frequency do u ppl use over there?

**Comment by hayschan** [comment]
> @hayschan btw what frequency do u ppl use over there?
> 
> Since the module currently on it is for 915 and 868

We use 470 MHz. We will have to change the BoM to use a 470 MHz module instead.

**Comment by valzzu** [comment]
> > @hayschan btw what frequency do u ppl use over there?
> > 
> > Since the module currently on it is for 915 and 868
> 
> We use 470 MHz. We will have to change the BoM to use a 470 MHz module instead.

https://www.cdebyte.com/products/E22-400M30S/1

:)
