### ISSUE TITLE
firmware

### ISSUE THREAD

**Issue by lunneswang** [valzzu/meshtastic-pcbs#2]
Does the firmware use this firmware-nrf52_promicro_diy_tcxo-2.5.17.b4b2fd6.uf2?

**Comment by valzzu** [comment]
Yes, its the promicro diy tcxo

**Comment by lunneswang** [comment]
Does this pcb have no gps interface?

**Comment by valzzu** [comment]
not at the moment since i only use GPS on mobile nodes and this was made for solar nodes
